### PR TITLE
Pay Card area

### LINKED ISSUE #95: Pay Card naming
The name before the @ in the Lightning address should be the name for the card by default

Example:

8406f0@dev.lightning.space
Makes:
8406f0 Pay Card

### LINKED ISSUE #97: Remove the Bitcoin and lightning symbol
image

image

I understand why Bolt Card designed this logo and I think it's very successful for Bolt Card. A simpler logo is more suitable for our use case at DFX. 

The Bitcoin symbol and the lightning bolt should be removed and only these 3 lines should be displayed. Since there is then more space, the lines should be slightly larger.

Otherwise, I really like the current design.

### PR DESCRIPTION
**Pull request by Danswar**
closes https://github.com/DFXswiss/btc-wallet/issues/81 , closes https://github.com/DFXswiss/btc-wallet/issues/90, closes #97 , closes #95
IMG_A9FEB12F4531-1

### CODE REVIEW

**Comment by Danswar** [comment]
https://drive.google.com/file/d/17bHDD2z3lnsQ0Y32tDshbjSdlWyQtf35/view?usp=sharing

**Comment by TaprootFreak** [comment]
works!

**Review by TaprootFreak — APPROVED** [review]

**Comment by Danswar** [comment]
includes small improvements #81 #90

**Comment by Danswar** [comment]
#97  added to this branch

Screenshot 2024-06-25 at 1 15 39 PM

Screenshot 2024-06-25 at 1 20 12 PM

**Comment by Danswar** [comment]
Added #95 

Screenshot 2024-06-25 at 2 41 15 PM

**Pull request merged**
